### ISSUE TITLE
add extra_suffix, BUILD_NAME, and custom_modules folders.

### ISSUE THREAD

**Issue by greenfox1505** [godot-build-options-generator/godot-build-options-generator.github.io#12]
In my repo, I use these in my `profile.py`:

```
extra_suffix = "green_godot"
custom_modules = "../modules"
os.environ["BUILD_NAME"] = extra_suffix
```

A couple of fields for features like this would be nice.

**Comment by Calinou** [comment]
The current UI only offers boolean toggles via checkboxes, so adding text fields will be nontrivial.

Also, [`BUILD_NAME`](https://github.com/godotengine/godot/pull/51002) should probably exist as a SCons option, as overriding it using an environment variable in `custom.py` feels awkward.

**Comment by greenfox1505** [comment]
Yeah, BUILD_NAME should probably be flag.

Even just like a sample of how some that syntax works might be good for noobs.

I added text fields though. Didn't take too long. https://github.com/godot-build-options-generator/godot-build-options-generator.github.io/pull/13 (never heard of `alpine.js`, but it's pretty nifty)

**Comment by Calinou** [comment]
- Fixed by https://github.com/godot-build-options-generator/godot-build-options-generator.github.io/pull/13.
