### ISSUE TITLE
Prepare for the upcoming Godot 4.0 release

### ISSUE THREAD

**Issue by nyabinary** [godot-build-options-generator/godot-build-options-generator.github.io#9]
Godot 4.0 is almost here, as it's now in beta. The website should be updated to reflect new Godot 4.0 options. As it's not out, this is best placed in a separate branch in the repo and merged upstream once 4.0 stable is out.

**Comment by DeeJayLSP** [comment]
I was going to make a new issue, but decided to leave as a comment here to avoid duplicates.

Whether a module is editor-only or not was checked in their `config.py`.

## As of Godot 4 beta 16/Godot 3.5 the list of modules are:

### Both Godot 4.0 and 3.5:

	bmp
	camera
	csg
	dds
	enet
	freetype
	gdscript
	gltf (editor only in 3.x)
	gridmap
	hdr
	jpg
	jsonrpc
	mbedtls
	minimp3
	mobile_vr
	mono
	navigation
	ogg (used for different purposes)
	raycast (editor only in 3.x)
	regex
	squish
	svg
	tga
	theora
	upnp
	vhacd
	vorbis (used for different purposes)
	webp
	webrtc
	websocket
	webxr
	
### Both, editor only:

	cvtt
	denoise
	tinyexr
	xatlas_unwrap

### Exclusive to Godot 4:

	basis_universal
	glslang
	lightmapper_rd
	meshoptimizer
	msdfgen
	multiplayer
	noise
	openxr
	text_server_adv
	text_server_fb
	zip (is disabled along minizip)

### Godot 4 editor only:

    astcenc
    etcpak

### Exclusive to Godot 3.5:

	bullet
	gdnative
	opensimplex
	opus
	pvr
	stb_vorbis
	visual_script
	webm	

### Godot 3.5 Editor only:

	etc
	fbx
	lightmapper_cpu	


## Explaining the "different purposes":

- To play Theora videos, you need ogg (container), theora (video stream) and vorbis (audio stream).

- To play WebM videos (3.x only), you need webm (container, libvpx included for video stream), vorbis and opus (both possible audio streams).

- To play Ogg Vorbis audio, you need ogg + vorbis in 4.0, and stb_vorbis in 3.x.

Therefore, when doing an update for 4.0, the descriptions should be updated to match each version.
___

## Some module usages:

basis_universal: used to pack(editor only) and unpack basis_universal textures;

**Comment by DeeJayLSP** [comment]
Shouldn't this be closed as completed already?

**Comment by GorEldeen** [comment]
Godot 4 support yet??

**Comment by Calinou** [comment]
> Godot 4 support yet??

The current generator should work well enough with Godot 4, but I'll go through the list of modules soon and update it for 4.2.

**Comment by Calinou** [comment]
Fixed by https://github.com/godot-build-options-generator/godot-build-options-generator.github.io/commit/f89e4baf27d998a6195b7ea2fb3c441cbd770ff8.
